# Need to run this manually to build the module and upload it to a release
# NOTE: must create Release manually first!

name: Mod Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn zip-module
      - name: Get build version
        id: get_version
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV
      - name: Upload files to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "v${{ env.version }}" ./module.zip ./dist/module.json --clobber
