# Need to run this manually to build the module and upload it to a release
# NOTE: must create Release manually first!

name: Mod Builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn zip-module
      - name: Get Version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{  env.version }}
          name: v${{ env.version }}
          allowUpdates: true
          draft: false
          prerelease: false
          token: ${{secrets.GITHUB_TOKEN}}
          generateReleaseNotes: true
          artifacts: ./module.zip, ./dist/module.json
